begin;

create extension pg_protect_columns;

select
	plan(2);

create table test_table(
	id bigint primary key generated by default as identity,
	immutable_column text
);

create trigger _protect_columns_before_update
	before update on test_table for each row
	execute procedure protect_columns('immutable_column');

insert into test_table(
	id,
	immutable_column)
values (
	1,
	'immutable value');

select
	disable_protection_on_column('immutable_column');

select
	results_eq($$ update
			test_table
		set
			immutable_column = 'new value'
			where
				id = 1
			returning
				immutable_column $$, $$
			values ('new value') $$, 'A column with disabled protections can be updated.');

select
	re_enable_column_protection();

select
	throws_ok($$ update
			test_table
		set
			immutable_column = 'changed the value'
			where
				id = 1 $$, 'Modifying "immutable_column" is not allowed', 'The column cannot be updated after protection is re-enabled.');

select
	finish();

rollback;
